// Error
export const GET_ERRORS = 'GET_ERRORS'
export const SET_ERRORS = 'SET_ERRORS'
// Category
export const GET_CATEGORIES = 'GET_CATEGORIES'
// Product
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY'
export const GET_PRODUCTS_BY_SUB_CATEGORY = 'GET_PRODUCTS_BY_SUB_CATEGORY'
export const GET_PRODUCTS_BY_CHILD_CATEGORY = 'GET_PRODUCTS_BY_CHILD_CATEGORY'
export const GET_SEARCHED_PRODUCT = 'GET_SEARCHED_PRODUCT'
// Cart
export const CART_COUNT = 'CART_COUNT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const GET_CART = 'GET_CART'
export const CHANGE_CART_QUANTITY = 'CHANGE_CART_QUANTITY'
export const REMOVE_FORM_CART = 'REMOVE_FORM_CART'
// Auth
export const REGISTER_CUSTOMER = 'REGISTER_CUSTOMER'
export const LOGIN_CUSTOMER = 'LOGIN_CUSTOMER'
export const LOGOUT_CUSTOMER = 'LOGOUT_CUSTOMER'

