// Category
export const GET_CATEGORIES = 'GET_CATEGORIES'
// Product
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY'
export const GET_PRODUCTS_BY_SUB_CATEGORY = 'GET_PRODUCTS_BY_SUB_CATEGORY'
export const GET_PRODUCTS_BY_CHILD_CATEGORY = 'GET_PRODUCTS_BY_CHILD_CATEGORY'
export const GET_SEARCHED_PRODUCT = 'GET_SEARCHED_PRODUCT'
// Cart
export const CART_COUNT = 'CART_COUNT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const GET_CART = 'GET_CART'

